---
title: irenepolnyi.com
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- Rakefile
- README
gems:
- jekyll-default-layout
kramdown:
  smart_quotes:
  - apos
  - apos
  - quot
  - quot
